### ISSUE TITLE
Using with-correlation-id scope separates the parent span

### ISSUE THREAD

**Issue by manikmagar** [avioconsulting/mule-opentelemetry-module#71]
When `tracing:with-correlation-id` scope is used to change the correlation id, spans for all processors inside the scope gets separated from the original trace.

Example flow processors - 
![image](https://user-images.githubusercontent.com/877286/195988490-287a9eb8-dcd9-4fb7-8383-f374f30621b8.png)

Generated traces for this setup shows two traces - 
1. /api/* for api request received on apikit
2. create-shipment-sys for the flow ref inside the scope

![image](https://user-images.githubusercontent.com/877286/195988637-cc1225f5-9c16-4bc3-adb8-3e0a35e79c53.png)

**Comment by StephenGoodall** [comment]
hey @manikmagar - sorry for piggybacking on this, but i wondered if there is a way to get clearer names on APIKit calls?
Are there any config options to tell it to use parts of the http.target value as the trace name or something like that?

For example, _/api/v1/sessions/venues/001/events/321_ to be named as something like _/api/v1/sessions/venues/{**venueID**}/events/{**eventID**}_ rather than "/api/v1/*" for everything

**Comment by adesjardin** [comment]
@StephenGoodall - I think that is something that is worth looking into, could you create that as a separate issue that we can track?

**Comment by hamerpr** [comment]
Yes, we have noticed the same issue. Using the With CorrelationID scope creates a new Trace ID which is undesirable as we also use the With CorrelationID scope to use an incoming transaction reference to be able to track a transaction through our systems which cannot be traced by the Trace ID alone
