### ISSUE TITLE
Support renaming traces from APIKit calls

### ISSUE THREAD

**Issue by StephenGoodall** [avioconsulting/mule-opentelemetry-module#95]
Just raising as a separate issue for tracking 😄 

Are there any config options to tell the module to use parts of the http.target value as the trace name or something like that?

For example, /api/v1/sessions/venues/001/events/321 to be named as something like /sessions/venues/{venueID}/events/{eventID} rather than "/api/v1/*" for everything

**Comment by manikmagar** [comment]
Thanks for raising this @StephenGoodall. 

OpenTelemetry specification recommends using low cardinality values for span name and `/sessions/venues/{venueID}/events/{eventID}` fits in that specs. 

The only issue for that is - this RAML resource path isn't available anywhere during runtime and there is no reliable way to construct it with the data available in attributes. 

Consider a resource like this - `/sessions/venues/{venueID}/events/{eventID}/{id1}/{id2}`. For a sample request, HTTP target path will be `/api/sessions/venues/1/events/2/3/4`. Apikit will resolve all the URI parameters and populate the `attributes.uriParameters` `Hashmap` with key-value pairs. This is an **unsorted** map without any hints to which part of the URI it maps to. For unique values, a guess by the values might work but when two uri parameters have same values, it will be unreliable.

**Comment by manikmagar** [comment]
APIKit-generated flows, follow a naming convention - `{method}:{normalizedPath}:{contentTypeIfApplicable}:{apiKitConfigName}`. For example - 

<img width="447" alt="image" src="https://github.com/avioconsulting/mule-opentelemetry-module/assets/877286/6e855e5f-2c6d-40e7-9b62-442e63cb59f6">

If we utilize this convention to update the root transaction span name based on the flow APIKit routes too, we can build the low-cardinality pattern names representing target endpoints instead of a `/api/*`. 

Here is a POC output with that approach. The last two traces are represented by the actual URL Pattern suggested by OpenTelemetry Spec -

<img width="664" alt="image" src="https://github.com/avioconsulting/mule-opentelemetry-module/assets/877286/01e4a33c-804f-4d71-9fa3-54be040a753e">

The cons with this approach are -
- Dependency on the naming convention which is unlikely to change until the next major version of the APIKit module
- If execution fails before the APIKit routes to the target flow (eg. bad request validation 400), the traces are captured under `/api/*` which splits the traces under two different buckets for the same actual target URL
